
import { GoogleGenAI } from "@google/genai";
import { FormData, ApiResponse } from '../types';

const SYSTEM_INSTRUCTION = `You are a specialized B2B Venture Builder and Strategic Design Partner.
Your goal is to take a raw concept and turn it into a high-converting digital asset with a specific "Theme".

**TONE & STYLE RULES:**
*   **B2B & Bold:** No fluff. Talk to founders, agency owners, and investors.
*   **Specific:** Focus on capital, cash flow, approvals, and automation.
*   **Punchy:** Use short headlines and skimmable bullet lists.
*   **Capital Efficient:** Assume the user is funding-constrained and time-poor.

You will receive a structured JSON input. Analyze 'goal', 'templateUrl', 'techStack', etc.

### Path 1: Generate Code (Goal: GENERATE_CODE)

Your output must be a valid JSON object containing a "Site Spec", a "Section-by-Section Wireframe", and the "Code Skeleton".

**Output Structure:**
\`\`\`json
{
  "assistantOutput": {
    "outputType": "GENERATED_CODEBASE",
    "codebase": {
      "techStack": "STATIC_WEBSITE" | "NEXT_JS" | "EMBED_WIDGET" | "TEMPLATE_REPLICA",
      "theme": "AGENCY" | "SAAS_DASHBOARD" | ...,
      "siteSpec": { ... },
      "wireframe": [ ... ],
      "setupInstructions": "Markdown string...",
      "files": [ { "path": "filename.ext", "content": "..." } ],
      "previewHtml": "..."
    }
  }
}
\`\`\`

**Tech Stack Specifics:**

*   **ALL STACKS (SEO MANDATE):**
    *   **CRITICAL:** You MUST inject the following SEO tags into the \`<head>\` of \`index.html\` or \`layout.tsx\`:
        *   \`<title>\`: A compelling title format like "[Brand Name] - [Short Value Prop]".
        *   \`<meta name="description" content="...">\`: A concise 150-160 character summary of the core concept.
        *   \`<meta name="keywords" content="...">\`: 5-10 comma-separated keywords relevant to the specific niche.

*   **STATIC_WEBSITE:**
    *   **Files:** \`index.html\`, \`styles.css\`, \`README.md\`.
    *   **Design:** Modern, clean, responsive.
    *   **Animations:** Use \`reveal-on-scroll\` class on sections and \`parallax-bg\` on hero/banner backgrounds.

*   **NEXT_JS:**
    *   Standard App Router structure.
    *   Include \`README.md\`.
    *   Ensure metadata export in \`layout.tsx\` includes title and description.

*   **EMBED_WIDGET:**
    *   **Files:** \`widget.js\`, \`widget.css\`.
    *   **Note:** A demo \`index.html\` will be automatically generated by the system, so focus on the widget code itself.

*   **TEMPLATE_REPLICA:**
    *   Mimic the visual structure of the provided \`templateUrl\`.
    *   Fill with specific project copy.

---

### Path 2: Template Copywriting (Goal: GENERATE_COPY)

**Output Structure:**
\`\`\`json
{
  "assistantOutput": {
    "outputType": "AUTOMATED_BUILD_PACKAGE",
    "package": {
      "coreProjectFile": {
        "templateLink": "...",
        "structuredContentJson": { ... }
      },
      "aiCraftedStrategicCopy": {
         // Standard fields...
         "callsToAction": [ ... ]
      },
      "preliminaryBrandAssetPack": {
         "curatedColorPalette": [ ... ],
         "fontRecommendations": [ ... ],
         "imageAndIconBriefs": [
            { 
              "section": "Hero", 
              "brief": "Type: [Photography/3D Render/Illustration]. Mood: [Professional/Energetic/Calm]. Content: [Specific details of the scene]. Style: [Minimalist/Cinematic/Abstract]. (Must align with brand voice: {{brandVoice}})"
            },
            // REQUIREMENT: You MUST generate at least 4 distinct briefs covering different visual types (e.g., 1 Photorealistic Scene, 1 Abstract 3D shape, 1 UI Mockup, 1 Icon Set).
         ],
         "generatedImages": [
            { "section": "Hero", "imageUrl": "https://placehold.co/600x400/png?text=Hero+Image" },
            { "section": "Features", "imageUrl": "https://placehold.co/400x300/png?text=Features" }
            // MANDATORY: Generate 2-3 placeholder image objects for key sections (Hero, Features, etc.)
         ]
      }
    }
  }
}
\`\`\`

---

### Path 3: Advisory Report (Goal: PROVIDE_ADVISORY)

Output \`STRATEGIC_ADVISORY_REPORT\`.

---

### Constraints:
*   **JSON Only:** Output must be a valid JSON object.
*   **No Placeholders:** Write actual, strategic copy.
`;

export const generateVentureBuild = async (data: FormData): Promise<ApiResponse> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey || apiKey.trim() === '') {
    throw new Error("API Key is missing. Please add API_KEY to your environment variables (e.g. Vercel Project Settings).");
  }

  const ai = new GoogleGenAI({ apiKey });

  // Refine the goal description passed to the AI
  let goalDescription = "Generate Code/Website";
  if (data.goal === 'PROVIDE_ADVISORY') {
    goalDescription = "Provide an Advisory Report";
  } else if (data.goal === 'GENERATE_COPY') {
    goalDescription = `Generate High-Converting Copy for the provided template URL: ${data.templateUrl}`;
  } else if (data.techStack === 'TEMPLATE_REPLICA') {
    goalDescription = `Generate a Code Replica mimicking the structure of: ${data.templateUrl}`;
  } else {
    goalDescription = `Generate a ${data.techStack} codebase for a ${data.theme} project`;
  }

  const prompt = JSON.stringify({
    task: "Generate Venture Build Output",
    projectBrief: {
      projectName: data.projectName,
      coreConcept: data.coreConcept,
      brandName: data.brandName,
      brandVoice: data.brandVoice,
      keyFeatures: data.keyFeatures,
      primaryCTA: data.primaryCTA,
      templateUrl: data.templateUrl,
      techStack: data.techStack,
      theme: data.theme,
      assistantsGoal: goalDescription
    }
  }, null, 2);

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        responseMimeType: "application/json",
      },
    });

    const text = response.text;
    if (!text) {
      throw new Error("No response received from AI.");
    }

    return JSON.parse(text) as ApiResponse;
  } catch (error: any) {
    console.error("Error generating venture build:", error);
    // Improve error messaging for common issues
    if (error.message?.includes('API_KEY')) throw error;
    if (error.status === 403) throw new Error("API Key invalid or permissions denied.");
    if (error.status === 429) throw new Error("Rate limit exceeded. Please try again later.");
    throw error;
  }
};

export const generateProjectBrief = async (seedConcept?: string): Promise<Partial<FormData>> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey || apiKey.trim() === '') {
    throw new Error("API Key is missing. Please add API_KEY to your environment variables.");
  }

  const ai = new GoogleGenAI({ apiKey });

  const prompt = `You are a creative venture builder helper.
  ${seedConcept ? `The user has this initial concept: "${seedConcept}". Expand this into a full project brief.` : `Generate a unique, innovative, and viable tech startup concept.`}

  Output a JSON object with the following fields to help the user fill out their project brief form:
  - projectName: A catchy name for the project.
  - brandName: A short, memorable brand name (often same as project name).
  - coreConcept: A compelling 2-3 sentence value proposition and description.
  - brandVoice: One of ['Professional & Authoritative', 'Friendly & Approachable', 'Playful & Energetic', 'Minimalist & Clean', 'Luxury & Exclusive', 'Tech-Forward & Innovative'].
  - keyFeatures: An array of 3-5 distinct feature names.
  - primaryCTA: A strong call to action text (e.g., "Start Free Trial", "Get Early Access").

  Do not output markdown code blocks. Just the JSON.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      },
    });

    const text = response.text;
    if (!text) {
      throw new Error("No response received from AI.");
    }

    return JSON.parse(text) as Partial<FormData>;
  } catch (error: any) {
    console.error("Error generating project brief:", error);
    if (error.message?.includes('API_KEY')) throw error;
    if (error.status === 403) throw new Error("API Key invalid or permissions denied.");
    if (error.status === 429) throw new Error("Rate limit exceeded. Please try again later.");
    throw error;
  }
};
